export const BEGIN_API_CALL = 'BEGIN_API_CALL'
export const API_CALL_SUCCESS = 'API_CALL_SUCCESS'
export const API_CALL_ERROR = 'API_CALL_ERROR'

export const UNAUTHORIZED = 'UNAUTHORIZED'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'

export const USER_GET_RESPONSIBLES = 'USER_GET_RESPONSIBLES'
export const USER_GET_DASHBOARD_INFO = 'USER_GET_DASHBOARD_INFO'
export const USER_GET_NOTIFICATIONS = 'USER_GET_NOTIFICATIONS'

export const MEETING_GET_WEEK_MEETINGS = 'MEETING_GET_WEEK_MEETINGS'
export const GET_MEETING_INFO = 'GET_MEETING_INFO'
export const CREATE_MEETING = 'CREATE_MEETING'
export const CONFIRM_MEETING = 'CONFIRM_MEETING'
export const DECLINE_MEETING = 'DECLINE_MEETING'

export const DELETE_MEETING = 'DELETE_MEETING'

export const TEAM_GET_INFO = 'TEAM_GET_INFO'

export const GET_LOGS = 'GET_LOGS'
export const DELETE_NOTIFICATION = 'DELETE_NOTIFICATION'
export const DELETE_ALL_NOTIFICATIONS = 'DELETE_ALL_NOTIFICATIONS'
